version: '3.7'
services:

  quarkus-app:
    image: quarkus/suprema
    container_name: quarkus-app
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/mydb
      - QUARKUS_DATASOURCE_USERNAME=user
      - QUARKUS_DATASOURCE_PASSWORD=password
      - QUARKUS_DATASOURCE_DRIVER=org.postgresql.Driver
    depends_on:
      - postgres
    networks:
      - quarkus-network

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - quarkus-network

networks:
  quarkus-network:
    driver: bridge
